Add `LiteJob::Server#kill` and `LiteJob::Server#exit` methods
litestack-ruby/litejob pull request #1
Opened 2023-08-25 12:42 UTC by marcoroth

This pull request adds two new methods `LiteJob::Server#kill` and `LiteJob::Server#exit` which can be used to stop a running `LiteJob::Server` instance.

Currently there is no public API to stop a `LiteJob::Server` from running and processing jobs, which this pull request is trying to address.

2023-09-04 16:56 UTC, fractaledmind requested changes

2023-09-04 16:56 UTC, fractaledmind commented on lib/litejob/server.rb
> +      end
You have a typo here with `@schedule` instead of `@scheduler`, plus I personally want to avoid one-line conditional nesting, and I'd like to have the return value suggest whether the call was effective or not:
```suggestion
      @scheduler&.context&.kill || false
```

2023-09-04 16:56 UTC, fractaledmind commented on lib/litejob/server.rb
> +      end
Ditto:
```suggestion
      @scheduler&.context&.exit || false
```

2023-09-04 19:18 UTC, marcoroth commented on lib/litejob/server.rb
> +      end
Whoops, good point. Updated 👍🏼

2023-10-18 21:27 UTC, fractaledmind approved these changes

2023-10-18 21:28 UTC, merged